---

- name: Packages | Use HTTPS
  copy:
    src: files/apt/sources.list
    dest: /etc/apt/sources.list
    mode: '644'

- name: Packages | Update
  apt:
    update_cache: yes
    upgrade: 'yes'

- name: Packages | Install - will take a long time
  package:
    name: "{{ apt_packages }}"
    state: present

- name: Packages | Cleanup
  apt:
    autoremove: yes
    autoclean: yes

- name: Packages | Update Gems
  shell: gem update --no-document && touch ~/.ansible-gems-updated
  args:
    creates: ~/.ansible-gems-updated

- name: System | Ensure kali user is configured correctly
  user:
    name: kali
    password: kali
    state: present

- name: AWS | Download AWS CLI
  get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip
    owner: kali
    group: kali
    mode: '660'
  register: awscli_archive

- name: AWS | Unarchive AWS CLI
  unarchive:
    src: '{{ awscli_archive.dest }}'
    remote_src: yes
    dest: /tmp
    mode: '660'
  register: new_awscli

- name: AWS | Install AWS CLI
  become: yes
  command: sh ./aws/install
  args:
    chdir: /tmp
    creates: /usr/local/bin/aws

- name: AWS | Update AWS CLI
  become: yes
  command: sh ./aws/install --update
  args:
    chdir: /tmp
  when: new_awscli.changed  # noqa 503

- name: AWS | Download SSM agent
  get_url:
    url: https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/debian_amd64/amazon-ssm-agent.deb
    dest: /tmp/amazon-ssm-agent.deb
    owner: kali
    group: kali
    mode: '660'

- name: AWS | Install SSM agent
  apt:
    deb: /tmp/amazon-ssm-agent.deb

- name: AWS | Start SSM agent
  systemd:
    name: amazon-ssm-agent
    state: started
    enabled: yes
  # Don't bother with systemd in the Molecule Docker container. Just skip testing this task.
  tags: notest
