---

#Packages to Install on instance by default
apt_packages:
  # All the default Kali tools
  - kali-linux-default
  # Everything below this should be in alphabetical order
  - dotdotpwn
  - exiftool
  - gobuster
  - gdb
  - kali-desktop-xfce
  - less
  # - libguestfs-tools # temporarily removed from kali-rolling on 2020-08-24
  - locate
  - magic-wormhole
  - oscanner
  - proxychains4
  - python-pip
  - python3-pip
  - python3-wheel
  - ruby-full
  - seclists
  - smtp-user-enum
  - software-properties-common
  - ssh-client
  - tigervnc-common
  - tigervnc-standalone-server
  - tigervnc-xorg-extension
  - tnscmd10g
  - ufw
  - wget
  - xz-utils

prepare_apt_packages:
  - python3
  - python3-apt
  - ssh

#############
# Passwords #
#############
# Password-based SSH is disabled, so similarly using this password requires already SSHing to the system as the kali user
kali_user_pass: kali

