---
name: CI

on: [pull_request]

jobs:
  Packer CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          make install-infra-build-tools
          pip install ansible
          ansible-galaxy install -r base-ami/ansible/requirements.yml

      - name: packer-validate
        run: packer validate -syntax-only base-ami/ami.json
    
      - name: packer-inspect
        run: packer inspect base-ami/ami.json

  Terraform CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: terraform-init
        run: cd base-ami/terraform && terraform init

      - name: terraform-format
        run: cd base-ami/terraform && terraform fmt -check

      - name: terraform-validate
        run: cd base-ami/terraform && terraform validate

      - name: terraform-plan
        run: cd base-ami/terraform && terraform plan  
